version: '3.8'

services:
  # --- HẠ TẦNG CHUNG ---
  mysql-store:
    image: mysql:8.0
    container_name: web-store-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: web_store
    networks:
      - internal-bridge
    volumes:
      - store_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-finance:
    image: postgres:15
    container_name: finance-db
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-rootpassword}
      POSTGRES_DB: finance_db
    networks:
      - internal-bridge
    volumes:
      - finance_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: message-broker
    ports:
      - "15672:15672" # Quản lý UI cho nhóm theo dõi
    networks:
      - internal-bridge

  api-gateway:
    image: kong:latest
    container_name: api-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000" # Cổng duy nhất cho Client truy cập
      - "8001:8001" # Admin API
    networks:
      - internal-bridge
      - public-net
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml

  # --- CÁC MODULE THÀNH VIÊN ---
  sync-service:
    build: ./module-1-inventory-sync
    container_name: module-sync
    depends_on:
      - mysql-store
    networks:
      - internal-bridge
    volumes:
      - ./input:/app/input
      - ./processed:/app/processed

  orders-service:
    build: ./module-2-orders-processing
    container_name: module-orders
    depends_on:
      - mysql-store
      - rabbitmq
    networks:
      - internal-bridge
    # KHÔNG mở ports trực tiếp ra ngoài

  control-center-service:
    build: ./module-3-control-center
    container_name: module-control
    depends_on:
      - postgres-finance
      - mysql-store
    networks:
      - internal-bridge
    # Đã xóa ports: "5002:5002" để đảm bảo tính bảo mật của Module 4

networks:
  internal-bridge:
    driver: bridge
  public-net:
    driver: bridge

volumes:
  store_data:
  finance_data:
